name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        # Aqui você pode adicionar seus comandos de teste, por exemplo:
        # python -m unittest discover -s tests
        flask run &  # Inicie a aplicação Flask em segundo plano
        sleep 5  # Aguarde alguns segundos para garantir que a aplicação esteja em execução
        curl -f http://localhost:5000/  # Verifique se a aplicação está acessível
